/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as MotoristaRouteImport } from './routes/motorista'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AcompanharIndexRouteImport } from './routes/acompanhar.index'
import { Route as AcompanharQueryRouteImport } from './routes/acompanhar.$query'
import { Route as ApiSupportChatRouteImport } from './routes/api/support-chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristaRoute = MotoristaRouteImport.update({
  id: '/motorista',
  path: '/motorista',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AcompanharIndexRoute = AcompanharIndexRouteImport.update({
  id: '/acompanhar/',
  path: '/acompanhar/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanharQueryRoute = AcompanharQueryRouteImport.update({
  id: '/acompanhar/$query',
  path: '/acompanhar/$query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSupportChatRoute = ApiSupportChatRouteImport.update({
  id: '/api/support-chat',
  path: '/api/support-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/motorista': typeof MotoristaRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/acompanhar/$query': typeof AcompanharQueryRoute
  '/api/support-chat': typeof ApiSupportChatRoute
  '/acompanhar/': typeof AcompanharIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/motorista': typeof MotoristaRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/acompanhar/$query': typeof AcompanharQueryRoute
  '/api/support-chat': typeof ApiSupportChatRoute
  '/acompanhar': typeof AcompanharIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/motorista': typeof MotoristaRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/acompanhar/$query': typeof AcompanharQueryRoute
  '/api/support-chat': typeof ApiSupportChatRoute
  '/acompanhar/': typeof AcompanharIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contato'
    | '/motorista'
    | '/planos'
    | '/privacidade'
    | '/reset-password'
    | '/sobre'
    | '/suporte'
    | '/termos'
    | '/dashboard'
    | '/acompanhar/$query'
    | '/api/support-chat'
    | '/acompanhar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contato'
    | '/motorista'
    | '/planos'
    | '/privacidade'
    | '/reset-password'
    | '/sobre'
    | '/suporte'
    | '/termos'
    | '/dashboard'
    | '/acompanhar/$query'
    | '/api/support-chat'
    | '/acompanhar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contato'
    | '/motorista'
    | '/planos'
    | '/privacidade'
    | '/reset-password'
    | '/sobre'
    | '/suporte'
    | '/termos'
    | '/_authenticated/dashboard'
    | '/acompanhar/$query'
    | '/api/support-chat'
    | '/acompanhar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContatoRoute: typeof ContatoRoute
  MotoristaRoute: typeof MotoristaRoute
  PlanosRoute: typeof PlanosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SobreRoute: typeof SobreRoute
  SuporteRoute: typeof SuporteRoute
  TermosRoute: typeof TermosRoute
  AcompanharQueryRoute: typeof AcompanharQueryRoute
  ApiSupportChatRoute: typeof ApiSupportChatRoute
  AcompanharIndexRoute: typeof AcompanharIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motorista': {
      id: '/motorista'
      path: '/motorista'
      fullPath: '/motorista'
      preLoaderRoute: typeof MotoristaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/acompanhar/': {
      id: '/acompanhar/'
      path: '/acompanhar'
      fullPath: '/acompanhar/'
      preLoaderRoute: typeof AcompanharIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhar/$query': {
      id: '/acompanhar/$query'
      path: '/acompanhar/$query'
      fullPath: '/acompanhar/$query'
      preLoaderRoute: typeof AcompanharQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/support-chat': {
      id: '/api/support-chat'
      path: '/api/support-chat'
      fullPath: '/api/support-chat'
      preLoaderRoute: typeof ApiSupportChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContatoRoute: ContatoRoute,
  MotoristaRoute: MotoristaRoute,
  PlanosRoute: PlanosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SobreRoute: SobreRoute,
  SuporteRoute: SuporteRoute,
  TermosRoute: TermosRoute,
  AcompanharQueryRoute: AcompanharQueryRoute,
  ApiSupportChatRoute: ApiSupportChatRoute,
  AcompanharIndexRoute: AcompanharIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
